import FilterGlobal from "@/components/rooms/filter-global";
import { useArgs, useEffect, useCallback } from "@storybook/preview-api";
import type { Meta, StoryObj } from "@storybook/react";
import { Room, Restaurants } from "@/utils/fetch";
import { Getdisable } from "@/components/rooms/room-complement/filter/functions";

const meta = {
  title: "Rooms/Room Filter Global",
  component: FilterGlobal,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
} satisfies Meta<typeof FilterGlobal>;

export default meta;

type Story = StoryObj<typeof meta>;

const Restaurant: Restaurants[] = [
  {
    id: 15,
    name: "Oleander Room",
    logo: "logo-oleander.gif",
    description: null,
  },
  {
    id: 155,
    name: "Cricketer's Pint",
    logo: "logo-cricketers_pint.gif",
    description: null,
  },
];

const rooms: Room[] = [
  {
    categoryId: 302,
    categoryCode: "R2",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Oceanview", "Pool", "Tropical Garden"],
    mapLocation: ["19", "20", "21"],
    imageCodes: ["328", "329", "331", "332"],
    name: "Italian Penthouse Oceanview Concierge Family Suite with Kids Room",
    description:
      'Featuring king size mahogany, four poster bed, adorned with a plush duvet, lounge sleeping chair, 42" flat screen TV plus a bar area with its own refrigerator and microwave. Kids enjoy mahogany bunk beds with a trundle, a 27" flat screen TV, a multi-function game table, a built-in nautical mahogany storage wall unit, its own closet and a vanity unit with basin and mirror. Bathroom hosts a two-basin mahogany vanity with a wall-mount makeup mirror and hair dryer, a whirlpool tub, a separate rainhead shower and a private water closet.',
    bedding: "1 king bed, 1 sleeper chair, 1 bunk bed w/trundle",
    maxOccupancy: 6,
    maxAdults: 3,
    transferType: "Airport",
    roomClass: "CLUB",
    webImgCode: "326",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-326-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-326.jpg",
    amenities: [
      {
        amenityId: 37,
        amenityName: "Balcony",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 44,
        amenityName: "King-Size Bed (Four-Poster)",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 41,
        amenityName: "Whirlpool Tub",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 72,
        amenityName: "His & Hers Bath Vanities",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 23,
        amenityName: "Plush His & Hers Robes",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 148,
        amenityName: "Walk In Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 4,
        amenityName: "In-Room Bar w/ Select Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 35076.6,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2705.5,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47303,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2654.4,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "R2",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: true,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 0,
        afterPromoRate: -2705.5,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 0,
        afterPromoRate: -2705.5,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 0,
        afterPromoRate: -2705.5,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-26",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 7730,
        afterPromoRate: 5024.5,
        adultPaxRate: 7190,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 7584,
        afterPromoRate: 4929.6,
        adultPaxRate: 7044,
        childPaxRate: 540,
        averageBaseRate: 7709.14,
        averageAfterPromoRate: 5010.94,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 28,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 28,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 28,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 28,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 28,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 28,
      },
    ],
  },
  {
    categoryId: 647,
    categoryCode: "1B2",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Tropical Garden"],
    mapLocation: ["24"],
    imageCodes: ["345", "346", "455"],
    name: "Key West Luxury One Bedroom Concierge Suite",
    description:
      "This one bedroom suite features a master bedroom with luxurious furnishings representing Key West. Each suite comes with a fully equipped kitchen with state of the art stainless steel appliances and granite countertops. There is a large living room with flat screen TV, twin trundle daybed and dining table. The master bedroom has a king sized bed, a spacious bathroom with granite vanity, a flat screen TV and a large balcony. The suite also features a second full bathroom to easily accommodate the needs of 5 guests. Includes concierge service.",
    bedding: "1 King Bed & 1 Trundle Bed (can accommodate a rollaway)",
    maxOccupancy: 5,
    maxAdults: 0,
    transferType: "Airport",
    roomClass: "CLUB",
    webImgCode: "344",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-344-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-344.jpg",
    amenities: [
      {
        amenityId: 37,
        amenityName: "Balcony",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 100,
        amenityName: "Dining Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 42,
        amenityName: "Flat Screen TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 106,
        amenityName: "Granite Countertops",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 98,
        amenityName: "King-Size Bed",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 45,
        amenityName: "Living Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 24,
        amenityName: "Sitting Area",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 4,
        amenityName: "In-Room Bar w/ Select Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 101,
        amenityName: "Kitchen",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 104,
        amenityName: "Stainless Steel Appliances",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 48504,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 65401,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "1B2",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: true,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-26",
        paxRate: 12126,
        afterPromoRate: 12126,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 12126,
        afterPromoRate: 12126,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 12126,
        afterPromoRate: 12126,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 12126,
        afterPromoRate: 12126,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 6929.14,
        averageAfterPromoRate: 6929.14,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 10,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 10,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 10,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 10,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 10,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 10,
      },
    ],
  },
  {
    categoryId: 468,
    categoryCode: "1BO",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Oceanview"],
    mapLocation: ["24"],
    imageCodes: ["298", "417"],
    name: "Key West Oceanview One Bedroom Concierge Suite",
    description:
      "This one bedroom suite features a master bedroom with luxurious furnishings representing Cape Cod and Key West. Each suite comes with a kitchen with a refrigerator and microwave with granite countertops. There is a large living room with a twin day bed with trundle, HD Smart TV and dining table. The master bedroom has a king sized bed and HD Smart TV. The bathroom includes a shower with granite vanity. The suite also features a large balcony with beautiful ocean views. These suites can also accommodate a rollaway.",
    bedding: "1 King Bed & 1 Trundle Bed (can accommodate a rollaway)",
    maxOccupancy: 5,
    maxAdults: 0,
    transferType: "Airport",
    roomClass: "CLUB",
    webImgCode: "297",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-297-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-297.jpg",
    amenities: [
      {
        amenityId: 37,
        amenityName: "Balcony",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 100,
        amenityName: "Dining Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 42,
        amenityName: "Flat Screen TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 106,
        amenityName: "Granite Countertops",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 98,
        amenityName: "King-Size Bed",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 45,
        amenityName: "Living Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 69,
        amenityName: "Bathtub",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 111,
        amenityName: "Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 4,
        amenityName: "In-Room Bar w/ Select Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 101,
        amenityName: "Kitchen",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 104,
        amenityName: "Stainless Steel Appliances",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 228,
        amenityName: "One-Bedroom Suite",
        amenityType: "Room Types",
        amenityCategory: "Room Types",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 0,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47222,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "1BO",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: true,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 2,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 2,
      },
    ],
  },
  {
    categoryId: 460,
    categoryCode: "4VP",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Beachfront", "Oceanfront", "Oceanview", "Pool"],
    mapLocation: ["8"],
    imageCodes: ["201", "204", "202", "203", "205", "206", "207", "421", "422"],
    name: "Key West Beachfront Four Bedroom Butler Villa Residence with Private Pool",
    description:
      "These villas are individual homes situated directly on the beach. Each villa has three floors. The first floor has a kitchen with a refrigerator, microwave and granite countertops, a fully furnished living room with sofa, chairs, HD Smart TV and dining room that can easily accommodate six people. There is also a bedroom on the first floor with a king bed, hardwood floors and HD Smart TV. The bathroom features a bathtub/ shower combination and granite vanity. The second floor boasts the master bedroom with a king bed, hard wood floors, HD Smart TV and walk-in closet. The master bath features an oversized jetted soaking tub with a walk-in shower and granite vanity. Third and fourth bedrooms are also on the second floor and feature a queen bed, hard wood floors and HD Smart TV's. The bathrooms have a bathtub/shower combination with granite vanities. The third floor boasts a comfortable sunroom or private patio overlooking the beach and ocean. Outside, there is a large porch, covered dry area and a private plunge pool. These rooms can also accommodate a rollaway. These accommodations offer Private Airport Transfers.",
    bedding: "2 Kings + 2 Queens, can accommodate 2 rollaways",
    maxOccupancy: 10,
    maxAdults: 0,
    transferType: "Private",
    roomClass: "BUTLER",
    webImgCode: "200",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-200-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-200.jpg",
    amenities: [
      {
        amenityId: 38,
        amenityName: "Patio",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 25,
        amenityName: "Private Pool",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 100,
        amenityName: "Dining Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 102,
        amenityName: "Double Beds",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 42,
        amenityName: "Flat Screen TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 20,
        amenityName: "In-Room Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 98,
        amenityName: "King-Size Bed",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 45,
        amenityName: "Living Room",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 99,
        amenityName: "Queen Bed",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 69,
        amenityName: "Bathtub",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 97,
        amenityName: "Bathtub/ Shower combination",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 72,
        amenityName: "His & Hers Bath Vanities",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 23,
        amenityName: "Plush His & Hers Robes",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 148,
        amenityName: "Walk In Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 131,
        amenityName: "Washer & Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 75,
        amenityName: "In-Room Bar w/ Premium Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 101,
        amenityName: "Kitchen",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 104,
        amenityName: "Stainless Steel Appliances",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 11,
        amenityName: "Butler Elite Service",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 142,
        amenityName: "Room Service",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 228,
        amenityName: "One-Bedroom Suite",
        amenityType: "Room Types",
        amenityCategory: "Room Types",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 79124.5,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47230,
        promotionName: "640-35% OFF KEY WEST VILLAGE",
        promotionDescription: "35% OFF RACK RATE",
        amount: 6086.5,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "4VP",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: true,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 17390,
        afterPromoRate: 11303.5,
        adultPaxRate: 16850,
        childPaxRate: 540,
        averageBaseRate: 17390,
        averageAfterPromoRate: 11303.5,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 2,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 5,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 6,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 6,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 6,
      },
    ],
  },
  {
    categoryId: 303,
    categoryCode: "PW",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Pool", "Tropical Garden"],
    mapLocation: ["15", "16", "17", "19", "20", "21"],
    imageCodes: ["339", "340", "341", "343"],
    name: "Italian Poolside Walkout Concierge Family Suite with Kids Room",
    description:
      'Featuring king size mahogany, four poster bed, adorned with a plush duvet, twin daybed with trundle, 42" flat screen TV plus a bar area with its own refrigerator and microwave. Kids enjoy mahogany bunk beds with a trundle, a 27" flat screen TV, a multi-function game table, a built-in nautical mahogany storage wall unit, its own closet and a vanity unit with basin and mirror. Bathroom hosts a two-basin mahogany vanity with a wall-mount makeup mirror and hair dryer, a whirlpool tub, a separate rainhead shower and a private water closet.',
    bedding: "1 king bed, 1 twin daybed w/trundle, 1 bunk bed w/trundle",
    maxOccupancy: 7,
    maxAdults: 3,
    transferType: "Airport",
    roomClass: "CLUB",
    webImgCode: "338",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-338-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-338.jpg",
    amenities: [
      {
        amenityId: 38,
        amenityName: "Patio",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 44,
        amenityName: "King-Size Bed (Four-Poster)",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 41,
        amenityName: "Whirlpool Tub",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 72,
        amenityName: "His & Hers Bath Vanities",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 23,
        amenityName: "Plush His & Hers Robes",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 148,
        amenityName: "Walk In Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 4,
        amenityName: "In-Room Bar w/ Select Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 175,
        amenityName: "Swim-up Suite",
        amenityType: "Room Types",
        amenityCategory: "Room Types",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 33228,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2564.1,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47302,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2507.4,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "PW",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: false,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 7326,
        afterPromoRate: 4761.9,
        adultPaxRate: 6786,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 7164,
        afterPromoRate: 4656.6,
        adultPaxRate: 6624,
        childPaxRate: 540,
        averageBaseRate: 7302.86,
        averageAfterPromoRate: 4746.86,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 30,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 30,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 30,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 30,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 30,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 30,
      },
    ],
  },
  {
    categoryId: 207,
    categoryCode: "FK",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Pool", "Tropical Garden"],
    mapLocation: ["1", "2", "3", "4", "5", "6", "7"],
    imageCodes: [],
    name: "French Village Luxury Room King",
    description:
      'Located within the picturesque "French Village" complex, with mahogany furniture. Second and third floor French windows open onto vistas of the village. Features a kind bed and a twin daybed with trundle.',
    bedding: "1 King bed & 1 twin daybed with trundle",
    maxOccupancy: 4,
    maxAdults: 0,
    transferType: "Airport",
    roomClass: "LUXURY",
    webImgCode: "407",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-407-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-407.jpg",
    amenities: [
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 0,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 25754,
        promotionName: "640-35% OFF FRENCH VIL BTC (FK)",
        promotionDescription: "35% OFF RACK RATE",
        amount: 0,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "FK",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: false,
    ratePerNight: [
      {
        rateDate: "2024-12-29",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 0,
        afterPromoRate: 0,
        adultPaxRate: 0,
        childPaxRate: 0,
        averageBaseRate: 0,
        averageAfterPromoRate: 0,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 51,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 51,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 51,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 51,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 51,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 52,
      },
    ],
  },
  {
    categoryId: 295,
    categoryCode: "M2P",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Oceanview", "Pool", "Tropical Garden"],
    mapLocation: ["20", "21"],
    imageCodes: ["251", "252", "253", "254", "255", "257", "258"],
    name: "Italian Oceanview Penthouse Two Bedroom Butler Family Suite",
    description:
      'Featuring king size mahogany, four poster bed, adorned with a plush duvet, lounge sleeping chair, 42" flat screen TV plus a bar area with its own refrigerator and microwave. Kids enjoy mahogany bunk beds with a trundle, a 27" flat screen TV, a multi-function game table, a built-in nautical mahogany storage wall unit, its own closet and a vanity unit with basin and mirror. Bathroom hosts a two-basin mahogany vanity with a wall-mount makeup mirror and hair dryer, a whirlpool tub, a separate rainhead shower and a private water closet. Connecting doors lead into living room with its daybed and trundle, sleeper sofa, cocktail table, lounge chair, desk, 42" flat screen TV, oval dining table with seating for six, wet bar, butler\'s pantry with refrigerator and microwave, full closet and bathroom.',
    bedding: "1 King bed, 1 sleeper chair, 1 bunk bed w/trundle, 1 daybed w/trundle, 1 sofa bed",
    maxOccupancy: 10,
    maxAdults: 0,
    transferType: "Private",
    roomClass: "BUTLER",
    webImgCode: "250",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-250-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-250.jpg",
    amenities: [
      {
        amenityId: 37,
        amenityName: "Balcony",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 44,
        amenityName: "King-Size Bed (Four-Poster)",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 41,
        amenityName: "Whirlpool Tub",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 72,
        amenityName: "His & Hers Bath Vanities",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 23,
        amenityName: "Plush His & Hers Robes",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 58,
        amenityName: "Slippers",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 148,
        amenityName: "Walk In Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 75,
        amenityName: "In-Room Bar w/ Premium Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 124,
        amenityName: "Wet Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 11,
        amenityName: "Butler Elite Service",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 142,
        amenityName: "Room Service",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 175,
        amenityName: "Swim-up Suite",
        amenityType: "Room Types",
        amenityCategory: "Room Types",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 6669.299999999996,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47310,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 4244.1,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "M2P",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: false,
    ratePerNight: [
      {
        rateDate: "2024-12-30",
        paxRate: 12126,
        afterPromoRate: 7881.9,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 5196.86,
        averageAfterPromoRate: 952.76,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 12126,
        afterPromoRate: 7881.9,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 5196.86,
        averageAfterPromoRate: 952.76,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 12126,
        afterPromoRate: 7881.9,
        adultPaxRate: 11586,
        childPaxRate: 540,
        averageBaseRate: 5196.86,
        averageAfterPromoRate: 952.76,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 4,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 4,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 4,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 4,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 4,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 4,
      },
    ],
  },
  {
    categoryId: 304,
    categoryCode: "T2",
    rstId: 3,
    resortName: "Beaches Turks & Caicos",
    rstCode: "BTC",
    categoryView: ["Oceanview", "Pool", "Tropical Garden"],
    mapLocation: ["19", "20", "21"],
    imageCodes: ["350", "351", "353", "327"],
    name: "Italian Oceanview Concierge Family Suite with Kids Room",
    description:
      'Featuring king size mahogany, four poster bed, adorned with a plush duvet, lounge sleeping chair, 42" flat screen TV plus a bar area with its own refrigerator and microwave.\r\nKids enjoy mahogany bunk beds with a trundle, a 27" flat screen TV, a multi-function game table, a built-in nautical mahogany storage wall unit, its own closet and a vanity unit with basin and mirror. Bathroom hosts a two-basin mahogany vanity with a wall-mount makeup mirror and hair dryer, a whirlpool tub, a separate rainhead shower and a private water closet.',
    bedding: "1 king bed, 1 sleeper chair, 1 bunk bed w/trundle",
    maxOccupancy: 6,
    maxAdults: 3,
    transferType: "Airport",
    roomClass: "CLUB",
    webImgCode: "348",
    thumbnailImgURL:
      "//cdn.sandals.com/beaches/v11/media/btc/accommodations/medium/btc-348-medium.jpg",
    fullImageURL: "//cdn.sandals.com/beaches/v11/media/btc/accommodations/large/btc-348.jpg",
    amenities: [
      {
        amenityId: 37,
        amenityName: "Balcony",
        amenityType: "Features",
        amenityCategory: "Features",
      },
      {
        amenityId: 9,
        amenityName: "Air Conditioning",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 53,
        amenityName: "Ceiling Fan",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 120,
        amenityName: "HD Smart TV w/ Cable",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 54,
        amenityName: "In-Room Electronic Safe",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 21,
        amenityName: "Iron & Ironing Board",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 44,
        amenityName: "King-Size Bed (Four-Poster)",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 128,
        amenityName: "Outlets 110 - 240 Volts",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 19,
        amenityName: "Telephone",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 41,
        amenityName: "Whirlpool Tub",
        amenityType: "Amenities",
        amenityCategory: "Bedroom & Living Spaces",
      },
      {
        amenityId: 13,
        amenityName: "Hair Dryer",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 72,
        amenityName: "His & Hers Bath Vanities",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 71,
        amenityName: "Make-up Mirror",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 23,
        amenityName: "Plush His & Hers Robes",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 18,
        amenityName: "Red Lane Spa Amenity Kit",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 148,
        amenityName: "Walk In Shower",
        amenityType: "Amenities",
        amenityCategory: "Bathroom & Laundry",
      },
      {
        amenityId: 14,
        amenityName: "Coffee and Tea Maker",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 157,
        amenityName: "Fully Stocked Bar",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 4,
        amenityName: "In-Room Bar w/ Select Liquor",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 3,
        amenityName: "Microwave",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 123,
        amenityName: "Refrigerator w/ Water, Juice & Sodas",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 153,
        amenityName: "Stocked w/ beer and wine",
        amenityType: "Amenities",
        amenityCategory: "Food & Drink",
      },
      {
        amenityId: 83,
        amenityName: "Airport Transfers",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 143,
        amenityName: "Daily Housekeeping",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 144,
        amenityName: "Nightly Turndown",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
      {
        amenityId: 114,
        amenityName: "WiFi",
        amenityType: "Amenities",
        amenityCategory: "Services",
      },
    ],
    restaurants: Restaurant,
    loveNest: false,
    afterPromoRate: 31573.1,
    pricePerNightPerAdult: 0,
    promotion: [
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-26",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-26",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-27",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-27",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-28",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-28",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-29",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-29",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-30",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-30",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2437.4,
        date: "2024-12-31",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2024-12-31",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
      {
        promotionId: 47301,
        promotionName: "640-35% OFF ITALIAN VILLAGE BTC",
        promotionDescription: "35% OFF RACK RATE",
        amount: 2376.5,
        date: "2025-01-01",
        sessionId: "452",
        roomCategory: "T2",
        reservationDate: "2025-01-01",
        primaryYN: "Y",
        factor: "PER_OCCUPANT",
      },
    ],
    discount: [],
    soldOut: false,
    ratePerNight: [
      {
        rateDate: "2024-12-26",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2024-12-27",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2024-12-28",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2024-12-29",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2024-12-30",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2024-12-31",
        paxRate: 6964,
        afterPromoRate: 4526.6,
        adultPaxRate: 6424,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
      {
        rateDate: "2025-01-01",
        paxRate: 6790,
        afterPromoRate: 4413.5,
        adultPaxRate: 6250,
        childPaxRate: 540,
        averageBaseRate: 6939.14,
        averageAfterPromoRate: 4510.44,
      },
    ],
    availability: [
      {
        reservationDate: "2024-12-26",
        availableRooms: 16,
      },
      {
        reservationDate: "2024-12-27",
        availableRooms: 16,
      },
      {
        reservationDate: "2024-12-29",
        availableRooms: 16,
      },
      {
        reservationDate: "2024-12-30",
        availableRooms: 16,
      },
      {
        reservationDate: "2024-12-31",
        availableRooms: 16,
      },
      {
        reservationDate: "2025-01-01",
        availableRooms: 16,
      },
    ],
  },
];

const DatafilterOptions = Getdisable(rooms);

export const Primary = {
  render: function Render(args) {
    const [{ newRoomMatch }, setRoomMatch] = useArgs();
    const [{ newRoomNotMatch }, setRoomNotMatch] = useArgs();
    const [DatamatchFilterOptions, setDatamatchFilterOptions] = useArgs();

    const handleRoomMatchChange = useCallback(
      (newRoomMatch: any) => {
        setDatamatchFilterOptions(Getdisable(newRoomMatch));
        setRoomMatch(newRoomMatch);
      },
      [setRoomMatch],
    );

    const handleRoomNotMatchChange = (newRoomNotMatch: any) => {
      setRoomNotMatch(newRoomNotMatch);
    };
    useEffect(() => {
      setDatamatchFilterOptions(Getdisable(rooms));
      console.log(DatamatchFilterOptions);
    }, []);

    return (
      <div className="flex flex-row flex-wrap">
        <FilterGlobal
          {...args}
          setRoomMatch={handleRoomMatchChange}
          setRoomNotMatch={handleRoomNotMatchChange}
          matchFilterOptions={DatamatchFilterOptions}
        />
      </div>
    );
  },
  args: {
    brand: "beaches",
    filterOptions: DatafilterOptions,
    rooms: rooms,
  },
} satisfies Story;
