export const resortURI = {
  SMB: "/montego-bay/",
  SRC: "/royal-caribbean/",
  BRP: "/royal-plantation/",
  SAT: "/grande-antigua/",
  SNG: "/negril/",
  SWH: "/south-coast/",
  SGO: "/ochi/",
  INN: "/sandals-inn/",
  SRB: "/royal-bahamian/",
  SEB: "/emerald-bay/",
  SLU: "/regency-la-toc/",
  SGL: "/grande-st-lucian/",
  SHC: "/halcyon-beach/",
  SLS: "/sandals-grenada/",
  SBD: "/sandals-barbados/",
  SBR: "/royal-barbados/",
  SCR: "/sandals-curacao/",
  SDR: "/dunns-river/",
  SSV: "/saint-vincent/",
  BBO: "/resorts/ocho-rios/",
  BNG: "/resorts/negril/",
  BTC: "/resorts/turks-caicos/",
};
